version: "3.2"

volumes:
  db_data:

services:
  postgres:
    image: postgres
    hostname: postgres
    container_name: postgres
    restart: always
    environment:
        POSTGRES_DB: app_db
        POSTGRES_USER: app_user
        POSTGRES_PASSWORD: secretpassword
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  adminer:
    image: adminer
    hostname: adminer
    container_name: adminer
    restart: always
    ports:
        - 8080:8080