export const artists = [
  {
    artist: 'King Gizzard & The Lizard Wizard',
    songs: [
      'Robot Stop',
      'Crumbling Castle',
      'Rattlesnake',
      'Gamma Knife',
      'Nuclear Fusion',
      'People-Vultures',
      'Work This Time',
      'The River',
      'Planet B',
      'Self-Immolate',
      'The Lord of Lightning',
      'Mars for the Rich',
      'Hell',
      'Murder of the Universe',
      'Fishing for Fishies',
      'Superbug',
      'Big Fig Wasp',
      'Billabong Valley',
      'Sleep Drifter',
      'Sense',
      'Venusian 1',
      'Organ Farmer',
      'Mr. Beat',
      'Han-Tyumi, the Confused Cyborg',
      'Perihelion',
      'Beginner’s Luck',
      'Cyboogie',
      'Altered Beast I',
      'Loyalty',
      'The Fourth Colour',
      'Horology',
      'Road Train',
      'Evil Death Roll',
      'Wah Wah',
    ]
  }
]